#!/bin/bash

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"

mocha -r $DIR/node_modules/coffeescript/register -r $DIR/node_modules/ts-node/register -r $DIR/node_modules/jsdom-global/register --require ignore-styles --recursive "test/**/*Tests.coffee"